OBJS_MODULE_SRC = ./src/parameter.o \
		  ./src/namelist.o \
		  ./src/com_var.o \
		  ./src/mim_var.o \
		  ./src/grads.o \
		  ./src/biseki.o \
		  ./src/biseki_y.o

OBJS_SRC = ./src/mim.o \
	   ./src/getpt.o \
	   ./src/getpt_etc.o \
	   ./src/intpl.o \
	   ./src/setpt0.o \
	   ./src/w_from_st.o \
	   ./src/epflux_div.o \
	   ./src/calendar.o \
	   ./src/fft.o \
	   ./src/undef.o \
	   ./src/integral.o \
	   ./src/get_pt_dot.o \
	   ./src/get_phi_dagger.o \
	   ./src/derivative.o \
	   ./src/mount_modify.o \
	   ./src/energy.o \
	   ./src/energy_conv.o \
	   ./src/energy_tendency.o \
	   ./src/check_range.o \
	   ./src/get_z_pt.o \
	   ./src/epflux.o \
	   ./src/gflux.o \
	   ./src/get_var_w_x_zm.o \
	   ./src/diabatic.o \
	   ./src/get_w.o
